### PR TITLE
Adapt PID controller from Selfie 3.0

### LINKED ISSUE #4: Apply PID control to follow specified path
Adapt PID controller from [Selfie 3.0](https://github.com/KNR-Selfie/selfie_f1tenth) to generate [steering commands](http://docs.ros.org/api/ackermann_msgs/html/msg/AckermannDriveStamped.html) given positional and angular offset, as defined in #29.

### PR DESCRIPTION
**Pull request by Goldob**
Resolves #4.

Most of the code has been copied from [F1/10 repository](https://github.com/KNR-Selfie/selfie_f1tenth), with the most notable difference being added support for two separate offset topics (position and angular). These topics are combined into one, fed into a PID controller and then the resulting effort is translated into [steering commands](http://docs.ros.org/melodic/api/ackermann_msgs/html/msg/AckermannDriveStamped.html). Automatic rescaling of Ki and Kd parameters based on vehicle speed is [also possible](https://github.com/KNR-Selfie/selfie_carolocup2019/blob/f6da955eae9806602a1b17f0d428ced0debe4688/src/selfie_control/scripts/offset_combiner.py).

Everything has been manually tested to work as desired, both on the level of individual nodes and as a complete subsystem. The last thing to do is find optimal parameters for the new car and put them into a single launch file. For now, the controller can be tuned by hand with [dynamic reconfiguration](http://wiki.ros.org/rqt_reconfigure) after running:

```bash
roslaunch selfie_control pid-tuning.launch
```

The above command will start all the required nodes working in the following layout:

pid-tuning

### CODE REVIEW

**Comment by nels3** [comment]
0) Building ok
1) Does command shouldn't be roslaunch selfie_control pid-tuning.launch? pid.tuning.launch file is inside selfie_control not selfie_launch
2) Do I need to have another rosrun? After running command after roscore I have one red line like cannot launch node of pid type. After it I have process [...] started with pid [...] and so on.
3) Should I test here sth?

**Comment by Goldob** [comment]
Ad 1. You are correct, my mistake. Fixed now :wrench:
Ad 2. The launch file should work out of the box, without additional node prerequisites. Please share the whole command line output you get after running the command.
Ad 3. Mainly sanity checks, which you've already done. I also need you to look over the launch file and individual nodes to understand how they interconnect and if the solution makes sense to you. Suggestions for code improvements are also welcome. I asked you to do the review because you know Python.

And last but not least, confirm if this fulfills the specification from the related issue.

**Comment by nels3** [comment]
Ad 2. There was missing package. I looked into pid-tuning file and there was PID package needed. When I installed it it works (so if somebody do not have this installed should do it). 
So now I have all four process started (before only three were starting), but after a couple of second pid_controller has error: process has died and inside log file there is pid parameters. I think it is not sth wrong with code rather my virtual machine, what do you think?

**Comment by Goldob** [comment]
The `pid` package is specified as dependency in `selfie_control`, so it should be installed automatically when running the commands from [repo's readme](https://github.com/KNR-Selfie/selfie_carolocup2019/blob/master/README.md).

The _process has died_ thing looks very strange. Perhaps you launched twice and there was a collision between node names? Could you restart everything, invoke `roslaunch` again and paste its output here?

**Comment by Goldob** [comment]
Seems like this sometimes just happens for some reason. Here is a [similar issue](https://bitbucket.org/AndyZe/pid/issues/11/servo_simlaunch-error) with launch file from the official `pid` package repository. Talking about _works on my machine_...

Could you run `roslaunch pid servo_sim.launch` and check if it also crashes?

In the meantime, I will try and dig into that :grimacing:

**Comment by nels3** [comment]
Yeah, same. One process (left wheel pid) died, other works and there are are new windows opened. Same message as in that link, but other process dies but after "ROS_INFO prev_time is 0, doing nothing" not before.

**Pull request merged**
